<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.0" />
    <PackageReference Include="JWT" Version="10.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServerCore\ServerCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Common\Protocol\Enum.proto" Link="Packet\Schema\Enum.proto" />
    <None Include="..\..\Common\Protocol\Protocol.proto" Link="Packet\Schema\Protocol.proto" />
    <None Include="..\..\Common\Protocol\Struct.proto" Link="Packet\Schema\Struct.proto" />
    <None Include="..\GenProto.bat" Link="GenProto.bat" />
    <None Include="..\GenProto.sh" Link="GenProto.sh" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Packet\Generated\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- PreBuildEvent -->
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Condition="'$(OS)' == 'Windows_NT'"
        Command="call &quot;$(SolutionDir)GenProto.bat&quot; &quot;$(SolutionDir)&quot; GameServer\Packet\Generated\ 1" />
    <Exec Condition="'$(OS)' != 'Windows_NT'" 
          Command="echo PreBuildEvent started on macOS/Linux &amp;&amp; chmod +x $(ProjectDir)../GenProto.sh &amp;&amp; $(ProjectDir)../GenProto.sh $(ProjectDir)../../ Server/GameServer/Packet/Generated/ 1" />
  </Target>

  <!-- PostBuildEvent -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Condition="'$(OS)' == 'Windows_NT'"
        Command="call &quot;$(SolutionDir)GenProto.bat&quot; &quot;$(SolutionDir)&quot; ..\Client\Assets\@Scripts\Packet\Generated\ 0" />
    <Exec Condition="'$(OS)' != 'Windows_NT'" 
          Command="echo PostBuildEvent started on macOS/Linux &amp;&amp; chmod +x $(ProjectDir)../GenProto.sh &amp;&amp; $(ProjectDir)../GenProto.sh $(ProjectDir)../../ Client/Assets/@Scripts/Packet/Generated/ 0" />
  </Target>

</Project>
