// <auto-generated />
using System;
using GameDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDB.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250909153630_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDB.AchievementClearListDb", b =>
                {
                    b.Property<int>("AchievementClearListDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementClearListDbId"));

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("AchievementClearListDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("AchievementClearList");
                });

            modelBuilder.Entity("GameDB.AchievementSaveDataDb", b =>
                {
                    b.Property<int>("AchievementSaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementSaveDataDbId"));

                    b.Property<bool>("IsCleared")
                        .HasColumnType("bit");

                    b.Property<int>("MissionState")
                        .HasColumnType("int");

                    b.Property<int>("OriginalTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("StackedPoint")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("AchievementSaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("AchievementSaveData");
                });

            modelBuilder.Entity("GameDB.BuddySaveDataDb", b =>
                {
                    b.Property<int>("BuddySaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuddySaveDataDbId"));

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("BuddySaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("BuddySaveData");
                });

            modelBuilder.Entity("GameDB.CurrencyDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("BlueGem")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("GreenGem")
                        .HasColumnType("int");

                    b.Property<int>("ScrollArmor")
                        .HasColumnType("int");

                    b.Property<int>("ScrollBelt")
                        .HasColumnType("int");

                    b.Property<int>("ScrollBoots")
                        .HasColumnType("int");

                    b.Property<int>("ScrollGloves")
                        .HasColumnType("int");

                    b.Property<int>("ScrollRing")
                        .HasColumnType("int");

                    b.Property<int>("ScrollWeapon")
                        .HasColumnType("int");

                    b.Property<int>("StoneArmor")
                        .HasColumnType("int");

                    b.Property<int>("StoneBelt")
                        .HasColumnType("int");

                    b.Property<int>("StoneBoots")
                        .HasColumnType("int");

                    b.Property<int>("StoneGloves")
                        .HasColumnType("int");

                    b.Property<int>("StoneRing")
                        .HasColumnType("int");

                    b.Property<int>("StoneWeapon")
                        .HasColumnType("int");

                    b.Property<int>("YellowGem")
                        .HasColumnType("int");

                    b.HasKey("PlayerDbId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("GameDB.HeroSaveDataDb", b =>
                {
                    b.Property<int>("HeroSaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroSaveDataDbId"));

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("MaxExp")
                        .HasColumnType("int");

                    b.Property<int>("NowExp")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("HeroSaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("HeroSaveData");
                });

            modelBuilder.Entity("GameDB.MissionSaveDataDb", b =>
                {
                    b.Property<int>("MissionSaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionSaveDataDbId"));

                    b.Property<int>("MissionState")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("StackedPoint")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("MissionSaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("MissionSaveData");
                });

            modelBuilder.Entity("GameDB.PlayerDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<bool>("BGMOn")
                        .HasColumnType("bit");

                    b.Property<bool>("EffectSoundOn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMissionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerDbId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameDB.StageClearDb", b =>
                {
                    b.Property<int>("StageClearDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageClearDbId"));

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("isClear")
                        .HasColumnType("bit");

                    b.Property<bool>("isEnable")
                        .HasColumnType("bit");

                    b.HasKey("StageClearDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("StageClear");
                });

            modelBuilder.Entity("GameDB.AchievementClearListDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("AchievementClearList")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.AchievementSaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Achievements")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.BuddySaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Buddies")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.CurrencyDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithOne("Currency")
                        .HasForeignKey("GameDB.CurrencyDb", "PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.HeroSaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Heroes")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.MissionSaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Missions")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.StageClearDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("StageClears")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.PlayerDb", b =>
                {
                    b.Navigation("AchievementClearList");

                    b.Navigation("Achievements");

                    b.Navigation("Buddies");

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("Heroes");

                    b.Navigation("Missions");

                    b.Navigation("StageClears");
                });
#pragma warning restore 612, 618
        }
    }
}
