// <auto-generated />
using System;
using GameDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDB.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251013110437_RemoveIsClearInAchievementSaveDataDb")]
    partial class RemoveIsClearInAchievementSaveDataDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDB.AchievementClearListDb", b =>
                {
                    b.Property<int>("AchievementClearListDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementClearListDbId"));

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("AchievementClearListDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("AchievementClearList");
                });

            modelBuilder.Entity("GameDB.AchievementSaveDataDb", b =>
                {
                    b.Property<int>("AchievementSaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementSaveDataDbId"));

                    b.Property<int>("MissionState")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("StackedPoint")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("AchievementSaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("AchievementSaveData");
                });

            modelBuilder.Entity("GameDB.AchievementValueDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("BuddyGacha")
                        .HasColumnType("int");

                    b.Property<int>("BuddyLevelUp")
                        .HasColumnType("int");

                    b.Property<int>("BuddySkillUp")
                        .HasColumnType("int");

                    b.Property<int>("ConsumGold")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyGacha")
                        .HasColumnType("int");

                    b.Property<int>("HeroGacha")
                        .HasColumnType("int");

                    b.Property<int>("HeroLevelUp")
                        .HasColumnType("int");

                    b.Property<int>("HeroSkillUp")
                        .HasColumnType("int");

                    b.Property<int>("MonsterKill")
                        .HasColumnType("int");

                    b.Property<int>("StageClear")
                        .HasColumnType("int");

                    b.HasKey("PlayerDbId");

                    b.ToTable("AchievementValue");
                });

            modelBuilder.Entity("GameDB.BuddyGachaLogDb", b =>
                {
                    b.Property<long>("BuddyGachaLogDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BuddyGachaLogDbId"));

                    b.Property<string>("BuddyGachaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuddyTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Do")
                        .HasColumnType("int");

                    b.Property<int>("DoMax")
                        .HasColumnType("int");

                    b.Property<int>("DuplicateRewardCount")
                        .HasColumnType("int");

                    b.Property<int?>("DuplicateRewardType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<long>("UnixSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("BuddyGachaLogDbId");

                    b.ToTable("BuddyGachaLog");
                });

            modelBuilder.Entity("GameDB.BuddySaveDataDb", b =>
                {
                    b.Property<int>("BuddySaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuddySaveDataDbId"));

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedNumber")
                        .HasColumnType("int");

                    b.Property<string>("SkillTemplateIdString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("BuddySaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("BuddySaveData");
                });

            modelBuilder.Entity("GameDB.CurrencyDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("BlueGem")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("GreenGem")
                        .HasColumnType("int");

                    b.Property<int>("ScrollArmor")
                        .HasColumnType("int");

                    b.Property<int>("ScrollBelt")
                        .HasColumnType("int");

                    b.Property<int>("ScrollBoots")
                        .HasColumnType("int");

                    b.Property<int>("ScrollGloves")
                        .HasColumnType("int");

                    b.Property<int>("ScrollRing")
                        .HasColumnType("int");

                    b.Property<int>("ScrollWeapon")
                        .HasColumnType("int");

                    b.Property<int>("StoneArmor")
                        .HasColumnType("int");

                    b.Property<int>("StoneBelt")
                        .HasColumnType("int");

                    b.Property<int>("StoneBoots")
                        .HasColumnType("int");

                    b.Property<int>("StoneGloves")
                        .HasColumnType("int");

                    b.Property<int>("StoneRing")
                        .HasColumnType("int");

                    b.Property<int>("StoneWeapon")
                        .HasColumnType("int");

                    b.Property<int>("YellowGem")
                        .HasColumnType("int");

                    b.HasKey("PlayerDbId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("GameDB.CurrencyGachaLogDb", b =>
                {
                    b.Property<long>("CurrencyGachaLogDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CurrencyGachaLogDbId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Do")
                        .HasColumnType("int");

                    b.Property<int>("DoMax")
                        .HasColumnType("int");

                    b.Property<int>("GachaItemResult")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<long>("UnixSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("CurrencyGachaLogDbId");

                    b.ToTable("CurrencyGachaLog");
                });

            modelBuilder.Entity("GameDB.HeroGachaLogDb", b =>
                {
                    b.Property<long>("HeroGachaLogDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HeroGachaLogDbId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Do")
                        .HasColumnType("int");

                    b.Property<int>("DoMax")
                        .HasColumnType("int");

                    b.Property<int>("GachaItemResult")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<long>("UnixSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("HeroGachaLogDbId");

                    b.ToTable("HeroGachaLog");
                });

            modelBuilder.Entity("GameDB.HeroSaveDataDb", b =>
                {
                    b.Property<int>("HeroSaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroSaveDataDbId"));

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("MaxExp")
                        .HasColumnType("int");

                    b.Property<int>("NowExp")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<string>("SkillTemplateIdString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("HeroSaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("HeroSaveData");
                });

            modelBuilder.Entity("GameDB.MissionSaveDataDb", b =>
                {
                    b.Property<int>("MissionSaveDataDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionSaveDataDbId"));

                    b.Property<int>("GetRewardCount")
                        .HasColumnType("int");

                    b.Property<int>("MissionState")
                        .HasColumnType("int");

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("StackedPoint")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("MissionSaveDataDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("MissionSaveData");
                });

            modelBuilder.Entity("GameDB.PlayerDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<bool>("BGMOn")
                        .HasColumnType("bit");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<bool>("EffectSoundOn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMissionTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastStaminaUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerDbId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameDB.StageClearDb", b =>
                {
                    b.Property<int>("StageClearDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageClearDbId"));

                    b.Property<int>("PlayerDbId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("isClear")
                        .HasColumnType("bit");

                    b.Property<bool>("isEnable")
                        .HasColumnType("bit");

                    b.HasKey("StageClearDbId");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("StageClear");
                });

            modelBuilder.Entity("GameDB.AchievementClearListDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("AchievementClearList")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.AchievementSaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Achievements")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.AchievementValueDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithOne("AchievementValues")
                        .HasForeignKey("GameDB.AchievementValueDb", "PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.BuddySaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Buddies")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.CurrencyDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithOne("Currency")
                        .HasForeignKey("GameDB.CurrencyDb", "PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.HeroSaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Heroes")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.MissionSaveDataDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Missions")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.StageClearDb", b =>
                {
                    b.HasOne("GameDB.PlayerDb", "Player")
                        .WithMany("Stages")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameDB.PlayerDb", b =>
                {
                    b.Navigation("AchievementClearList");

                    b.Navigation("AchievementValues")
                        .IsRequired();

                    b.Navigation("Achievements");

                    b.Navigation("Buddies");

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("Heroes");

                    b.Navigation("Missions");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
